Panic on unsafe shell
mTvare6/hello-world.rs pull request #262
Opened 2022-05-10 07:51 UTC by guangmuzhu

Printing on unknown shell is totally unsafe, and the 'panic!()' is the perfect solution!

# Pull request

##### Fill either one
- [ ] Does your pull request add a crate?
- [ ] Does your pull request add a new language?

- [x] Is your pull request memory safe?
- [x] Is your pull request configurable?
- [x] Is your pull request minimal?
- [x] Is your pull request blazing fast?

2022-05-28 06:31 UTC, mTvare6 commented
```diff
-                                             panic!("Oh dear, your shell is UNSAFE!");
+                                            panic!("Oh dear, your shell is UNSAFE!\n But don't worry, rust is so safe, it'll quite immediatly!");
```

2022-06-11 18:06 UTC, TheDevMinerTV requested changes

2022-06-11 18:06 UTC, TheDevMinerTV commented on src/main.rs
> +                                            panic!("Oh dear, your shell is UNSAFE!\n But don't worry, rust is so safe, it'll quite immediatly!");
```suggestion
                                            panic!("Oh dear, your shell is UNSAFE!\n But don't worry, rust is so safe, it'll quit immediately!");
```

2022-06-30 10:42 UTC, mTvare6 commented
Thanks, now we can replace all bad unsafe c programs like `echo` with very minimal, blazing fast, and configurable `hello-world`

2022-06-30 10:42 UTC, merged